### ISSUE TITLE
Small Bug with non-constant density contrast

### ISSUE THREAD

**Issue by LL-Geo** [mdtanker/invert4geom#77]
**Describe the bug**
I had some fun playing the package. Well done and nice design @mdtanker 👍!

Just find a small bug that when the input density is non-constant, it will still force the density contrast to be constant. And of course the topography is very off in these wrong density region.

![image](https://github.com/mdtanker/invert4geom/assets/54405391/4294a604-f25e-4ccb-9f44-36d7a70f4fa1)
![image](https://github.com/mdtanker/invert4geom/assets/54405391/7742059e-aac6-43dc-9cf7-289550f612da)

**Full code that generate the error**

```python
# the density contrast is between rock (~2670 kg/m3) and air (~1 kg/m3)
density_contrast1 = 2670 - 1
density_contrast2 = 1322

# prisms are created between the mean topography value and the height of the topography
zref = true_topography.values.mean()

# prisms above zref have positive density contrast and prisms below zref have negative
# density contrast
density_grid = xr.where(true_topography > zref, density_contrast1, -density_contrast2)
```

That should be easy to fix In
```python
def update_prisms_ds(
    prisms_ds: xr.Dataset,
    correction_grid: xr.DataArray,
    zref: float,
) -> xr.Dataset:
```
Change 
```python
    density_contrast = ds.density.values.max()
```
To
```python
   density_contrast = np.fabs(ds.density)
```
This should solve the issue.😁

**Comment by mdtanker** [comment]
Hey @LL-Geo thanks for checking out the package! Yes that's a good catch, I've only been using constant densities so far, but yes we should allow variable densities. The only other place it may need some work to implement would be the density cross validation. I think we would just need to clarify in the documentation that the density CV only works for constant density values. Maybe there could be some scheme for a CV for finding the optimal density values for different regions, i.e. do a   CV to find optimal density for 1 region based on a mask, then do another CV for the remaining areas.

I'll try and implement you fix I'm the next few weeks, or if you need it soon feel free to raise a PR!

**Comment by mdtanker** [comment]
Yeah that sounds great, happy to implement that at some point! Thanks for sharing that paper, don't think I had seen that one yet.

**Comment by LL-Geo** [comment]
> Yeah that sounds great, happy to implement that at some point! Thanks for sharing that paper, don't think I had seen that one yet.

haha.. looking forward to it 😉
